//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string POB { get; set; }
        public string Note { get; set; }
    }
}
