//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStock
    {
        public string SID { get; set; }
        public string StaffID { get; set; }
        public string Suplier { get; set; }
        public string ImportDate { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual BookStockDetail BookStockDetail { get; set; }
    }
}
