//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookWesteReport
    {
        public string ID { get; set; }
        public string Staff { get; set; }
        public string BookID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Qty { get; set; }
        public string Note { get; set; }
    
        public virtual Staff Staff1 { get; set; }
    }
}
