//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookPrice
    {
        public string ID { get; set; }
        public string BookID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Supplier { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
    
        public virtual Supplier Supplier1 { get; set; }
    }
}
